config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/login", to: "sessions#new", as: "user_login"
  get "/logout", to: "sessions#destroy", as: "user_logout"
  post "/sessions", to: "sessions#create"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"

  # get "/cities", to: "cities#index", as: "cities"
  # get "/cities/new", to: "cities#new", as: "new_city"
  # post "/cities", to: "cities#create"
  # get "/cities/:id", to: "cities#show", as: "city"

  # get "/cities/:city_id/posts", to: "posts#index", as: "city_posts"
  # get "/cities/:city_id/posts/new", to: "posts#new", as: "new_city_post"
  # post "/cities/:city_id/posts", to: "posts#create"
  # get "/cities/:city_id/posts/:id", to: "posts#show", as: "city_post"
  # get "/cities/:city_id/posts/:id/edit", to: "posts#edit"
  # patch "/cities/:city_id/posts/:id", to: "posts#update"
  # delete "/cities/:city_id/posts/:id", to: "posts#destroy"

  resources :cities, shallow: true, except: [:destroy] do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts

  def self.find_by_slug(slug)
    find_by_city(slug.gsub('-', ' ').titleize)
  end

  def to_param
    city.downcase.gsub(" ", "-")
  end

  alias_method :city, :name

  # def name
  #   city
  # end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :city
  validates :title, presence: true, length: { minimum: 1,  maximum: 200 }
  validates :text, presence: true, length: { minimum: 1, maximum: 10000 }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts

  has_secure_password

  validates :first_name, :last_name, :city, :state, presence: true, length: { maximum: 255 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email,
            presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: true,
            length:     { maximum: 255 }

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
    @city = City.find_by_id(params[:id])
    render :index
  end

  def new
    @city = City.new
    render :new
  end

  def create
    @city = City.create(city_params)
    redirect_to @city
  end

  def show
    @city = City.find_by_slug(params[:id])
  end

  private

  def city_params
    params.require(:city).permit(:city, :state, :country, :image)

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_city, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_ownership!, only: [:edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @city.posts << @post
    if @post.save
      flash[:success] = "Post created succesfully to #{@city.name}!"
      redirect_to city_path(@city)
    else
      flash[:error] = @post.errors.full_messages.join(", ")
      redirect_to new_city_post_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @post.update(post_params)
    flash[:notice] = "Post update succesful!"
    redirect_to city_post_path
  end

  def destroy
    @post.destroy
    flash[:error] = "Post succesfully deleted!"
    redirect_to city_path(@city)
  end


  private

    def require_ownership!
      if !current_user_is_owner?
        flash[:errror] = "You must be logged in as #{@post.user.first_name}"
        redirect_to user_login_path
      end
    end

    def set_city
      @city = City.find_by_slug(params[:city_id])
    end

    def set_post
      @post = Post.find_by_id(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :text)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      flash[:success] = "Login successful. Welcome!"
      login(@user)
      redirect_to @user
    else
      flash[:error] = "Incorrect email or password. Please try again."
      redirect_to user_login_path
    end
  end

  def destroy
    flash[:success] = "Logout succesful. See you soon!"
    logout
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      render :index
    else
      @users = User.all
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      NewUserEmailMailer.notify_user(@user).deliver
      flash[:success] = "Succesfully created account."
      login(@user)
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def show
    @post = Post.find_by_id(params[:post_id])
    @city = City.find_by_id(params[:city_id])
    @user = User.find_by_id(params[:id])
  end

  def edit
    @user = User.find_by_id(params[:id])
    if session[:user_id] != @user[:id]
      flash[:error] = "Sorry! You can only edit your own profile."
      redirect_to user_path
    else
      render :edit
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(user_params)
    if session[:user_id] == @user.id
      flash[:success] = "Profile update succesful!"
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user)
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :city, :state, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def current_user_is_owner?
    session[:user_id] == @post.user_id
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def authenticate_user!
    redirect_to user_login_path unless current_user
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<span class="post center">
  <% @cities.each do |f| %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <div class="city_image">
            <img class=" cities responsive-image" src=<%=f.image%>>
          </div>
          <div class="card-title"><%= link_to f.city, city_path(f) %></div>
          <p><%= f.state%></p>
          <p><%= f.country%></p>
        </div>
      </div>
  <% end %>
</div>

app/views/cities/new.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="col-md-6">
      <%= form_for @city do |f| %>
        <div>
          <%= f.text_field :city, placeholder: "City" %>
        </div>
        <div>
          <%= f.text_field :state, placeholder: "State" %>
        </div>
        <div>
          <%= f.text_field :country, placeholder: "Country" %>
        </div>
        <div>
          <%= f.text_field :image, placeholder: "Image" %>
        </div>
        <%= f.submit "Add City", :class => 'waves-effect waves-light btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cities/show.html.erb
<div class="intro">
  <img class="jumbotron responsive-image" src=<%= @city.image %>>
  <h1 class="black-text text-lighten-5">Welcome to <%= @city.city %></h1>
</div>
<br>
<div class="post center">
  <%= link_to "Add new post!", new_city_post_path(@city), :class => "waves-effect waves-light btn" %>
  <% @city.posts.reverse_each do |post| %>
    <div class="col s6 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= link_to "#{post.title}", city_post_path(@city, post.id) %></span>
          <p><%= post.text %>
          <p>-<%= post.user.first_name %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Travel Forecast</h5>
        <p class="grey-text text-lighten-4">Weather API</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Collaborators</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Matt</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Meg</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Jason</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Switt</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2016
      <a class="grey-text text-lighten-4 right" href="https://github.com/mehgellan/vagabond_app"><i class="material-icons">email</i></a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="btn-floating btn-large waves-effect waves-light"><i class="material-icons">language</i></a>
        <ul class="right hide-on-med-and-down">
          <li>
            <% if current_user %>
              <div class="chip chip_left">
                <img src="http://www.eilatgordinlevitan.com/kurenets/k_pix/kunstler/060508_30_b.gif" alt="Contact Person">
                <%= current_user.first_name %> <%= current_user.last_name%></p>
              </div>
              <%= link_to "Profile", user_path(current_user[:id]), :class => "waves-effect waves-light btn" %>
              <%= link_to "Edit Profile", edit_user_path(current_user[:id]), :class => "waves-effect waves-light btn" %>
              <%= link_to "Logout", user_logout_path, :class => "waves-effect waves-light btn" %>
              <%= link_to "Browse Cities", cities_path, :class => "waves-effect waves-light btn"%>
            <% else %>
              <%= link_to "Login", user_login_path, :class => "waves-effect waves-light btn" %>
              <%= link_to "Sign Up", new_user_path, :class => "waves-effect waves-light btn" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagabondApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>

    <div class="header">
      <%= render 'layouts/header' %>
    </div>

    <% flash.each do |name, msg| %>
    <div class="card teal lighten-1">
      <div class="card-content white-text">
        <%= msg %>
      </div>
    </div>  
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/posts/edit.html.haml
.form-wrapper
  .container.title
    .col-md-6
    %h2 Welcome to our site!
    %p= @post.text
    %p= @post.user.first_name

app/views/posts/new.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="col-md-6">
      <%= form_for [@city, @post] do |f| %>
        <div>
          <%= f.text_field :title, placeholder: "Title" %>
        </div>

        <div>
          <%= f.text_area :text, placeholder: "Text"%>
        </div>

        <%= f.submit "Post", :class => 'waves-effect waves-light btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col s12 m7 top">
  <div>
  </div>
  <div class="card small horizontal color">
    <div class="card-image">
      <img src=<%= @city.image %>>
    </div>
    <div class="card-stacked">
      <div class="card-content">
        <h4><%= @post.title %></h4>
        <p><%= @post.text %></p>
      </div>
      <div class="card-content">
        <div class="chip">
          <img src="http://www.eilatgordinlevitan.com/kurenets/k_pix/kunstler/060508_30_b.gif" alt="Contact Person">
          <%= @post.user.first_name %> <%= @post.user.last_name%></p>
        </div>
         Member Since:  <%= @post.user.created_at.strftime("%d %b. %Y") %>
      </div>
      <% if current_user_is_owner? %>
      <div class="card-action" id="delete_edit">
        <%= link_to edit_post do %>
          <i class="small material-icons">mode_edit</i>
        <% end %>
        <%= link_to @post, method: :delete, data: { confirm: "Are you sure you want to delete #{@post.title}?" } do %>
          <i class="small material-icons">delete</i>
        <% end %>
        <span id="back">
          <%= link_to "Back to #{@city.city}", city_path(@city), class: 'link-to-text-color' %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="form-wrapper">
<div class="container">
<div class="col-md-6">
<%= form_for @user do |f| %>
  <div>
      <%= f.text_field :first_name, placeholder: "First Name" %>
    </div>
    <div>
      <%= f.text_field :last_name, placeholder: "Last Name" %>
    </div>
    <div>
      <%= f.text_field :email, placeholder: "Email" %>
    </div>
    <div>
      <%= f.text_field :city, placeholder: "City" %>
    </div>
    <div>
      <%= f.text_field :state, placeholder: "State" %>
    </div>
<%= f.submit "Submit", :class => 'waves-effect waves-light btn' %>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<body class="gif-background">
  <h1 id="splash"> VAGABOND </h1>
  <span><h5>Travel. Share. Discover.</h5></span>
</body>

app/views/users/new.html.erb
<body class="gif-background">
<div class="form-wrapper">
  <div class="container">
    <div class="col-md-6">
      <%= form_for @user do |f| %>
      <div>
        <%= f.text_field :first_name, placeholder: "First Name" %>
      </div>
      <div>
        <%= f.text_field :last_name, placeholder: "Last Name" %>
      </div>
      <div>
        <%= f.text_field :email, placeholder: "Email" %>
      </div>
      <div>
        <%= f.text_field :city, placeholder: "City" %>
      </div>
      <div>
        <%= f.text_field :state, placeholder: "State" %>
      </div>
      <div>
        <%= f.password_field :password, placeholder: "Password" %>
      </div>
      <%= f.submit "Submit", :class => 'waves-effect waves-light btn' %>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/users/show.html.erb
<div class="center">
  <div class="profile_image">
    <img src="http://www.eilatgordinlevitan.com/kurenets/k_pix/kunstler/060508_30_b.gif" alt="" class="circle responsive-img" width="200" height="200"></img>
  </div>
  <span class="profile_name">
    <%= @user.full_name %><br></span>
  <span class="location_name"><%= @user.city %>, <%=@user.state %><br></span>
  <div>
    <p><%= link_to "Browse Cities", cities_path %></p>
</div>
<% @user.posts.each do |f| %>
<div class="col s12 m7 profile_card">
  <div class="card small horizontal">
    <div class="card-stacked">
      <div class="card-content">
        <h4> <%= f.title %> </h4>
        <p><%= f.text %></p>
      </div>
    </div>
  </div>
</div>
<% end %>